apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    tektonci/build-namespace: ozone
    tektonci/pipeline-label-selector: 'pipeline.jquad.rocks/git.repository.branch.name=main'
    backstage.io/techdocs-ref: 'https://github.com/binkkatal/go-hello-world/blob/master/README.md'
    backstage.io/kubernetes-id: 'attachbeta'
  name: jquad-microservice
  description: JQuad Microservice
spec:
  type: service
  lifecycle: production
  owner: user:guest
